### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by randomaccess3** [randomaccess3/Awesome-BEC#12]
https://m365maps.com/
Msportals.io

**Comment by randomaccess3** [comment]
https://github.com/intrepidtechie/KITT-O365-Tool

**Comment by randomaccess3** [comment]
https://github.com/WillOram/AzureAD-incident-response

https://github.com/AzureAD/AzureADAssessment

**Comment by randomaccess3** [comment]
https://twitter.com/InvictusIR/status/1528705124683628545?t=5U8dNj-0SafWt3kWK0nSsw&s=19

**Comment by randomaccess3** [comment]
Spoofing Microsoft 365 Like It’s 1995 - https://www.blackhillsinfosec.com/spoofing-microsoft-365-like-its-1995/

**Comment by svch0stz** [comment]
https://github.com/invictus-ir/Microsoft-365-Extractor-Suite

**Comment by randomaccess3** [comment]
https://isc.sans.edu/diary/rss/28702

**Comment by randomaccess3** [comment]
https://www.youtube.com/watch?v=-90S8fMUprc

**Comment by randomaccess3** [comment]
https://github.com/dirkjanm/ROADtools

**Comment by randomaccess3** [comment]
https://dragonadvancetech.com/reports/M365%20Forensics%20Playbook_v3.pdf
